version: "2"
services:
  webserver:
#    image: phpstorm/php-apache:7.4-xdebug2.9
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - database

  database:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: bibliotheque
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  phpunit:
    image: phpstorm/php-cli:7.4-xdebug3.0
    ports:
      - "1080:80"
    volumes:
      - .:/opt/project/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
